### ISSUE TITLE
Citation annotation offset outside passage

### ISSUE THREAD

**Issue by jakelever** [jakelever/biotext#9]
Hey @creisle , I've come across a citation annotation that is outside the associated passage. One of my scripts checks some things on BioC files and this got flagged. I think that it doesn't seem right. What do you think?

Below is an example where the passage offset is 56733 but the zero-length citation is at offset 56732 which is just before the passage starts.

```
    <passage>
      <infon key="section">floating</infon>
      <infon key="subsection">None</infon>
      <infon key="xml_path">floats-group/table-wrap/table/thead</infon>
      <offset>56733</offset>
      <text> (µg/mL)    S-2366 K M (mM) V MAX (mAU/min)</text>
      <annotation id="ANN_c6f8f533-0764-4484-8663-c18655ca06f3">
        <infon key="citation_text">1</infon>
        <infon key="type">citation</infon>
        <location offset="56732" length="0"/>
        <text/>
      </annotation>
    </passage>
```

To reproduce, I've included the source PMC XML file: [PMC8466798.xml.gz](https://github.com/jakelever/biotext/files/7866691/PMC8466798.xml.gz) and I converted it with the line below.

```
python src/convert.py --i PMC008xxxxxx/PMC8466798.xml --iFormat pmcxml --o test.bioc.xml --oFormat biocxml
```

**Comment by creisle** [comment]
Sorry for the long delay, this completely fell off my radar. I've been debugging this and it looks like the reason this happens is a case where the citation is the first thing in a passage. Now since we remove the in-text citation and attribute it to the text that precedes it this ends up putting the annotation in the wrong passage. Should be an easy fix but first I'd like to see why those passages are being split. Seems like maybe they shouldn't be

**Comment by creisle** [comment]
![image](https://user-images.githubusercontent.com/4342641/223638652-a3cd2e30-f2f3-4b30-8d4c-f6e4e59bd195.png)

Ok this one is really weird.... the citation is actually in a strange position in the original text. Would it make sense to append it to the previous passage after the table description or should we just be adjusting the position so the reference is the start of the table header passage?

**Comment by jakelever** [comment]
Wow, what a weird one. Some bug in the publishers' code to convert to PMC XML. It's probably just better to work with the data that we've got instead of trying fixes that may sometimes work. So I guess insert it into the table header? What'd you think?

**Comment by creisle** [comment]
ya, that's probably the simplest solution
